package entities;
// Generated Dec 22, 2015 4:16:46 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assignment generated by hbm2java
 */
@Entity
@Table(name = "assignment", catalog = "learning")
public class Assignment implements java.io.Serializable {

	private Integer id;
	private Course course;
	private String name;
	private String comment;
	private String file;
	private Date endDate;
	private Set<Perform> performs = new HashSet<Perform>(0);

	public Assignment() {
	}

	public Assignment(Course course, String name, String comment, String file, Date endDate) {
		this.course = course;
		this.name = name;
		this.comment = comment;
		this.file = file;
		this.endDate = endDate;
	}

	public Assignment(Course course, String name, String comment, String file, Date endDate, Set<Perform> performs) {
		this.course = course;
		this.name = name;
		this.comment = comment;
		this.file = file;
		this.endDate = endDate;
		this.performs = performs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Course", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Comment", nullable = false, length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "File", nullable = false, length = 100)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EndDate", nullable = false, length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assignment")
	public Set<Perform> getPerforms() {
		return this.performs;
	}

	public void setPerforms(Set<Perform> performs) {
		this.performs = performs;
	}

}
