package entities;
// Generated Dec 23, 2015 8:10:44 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Courseregister generated by hbm2java
 */
@Entity
@Table(name = "courseregister", catalog = "learning")
public class Courseregister implements java.io.Serializable {

	private CourseregisterId id;
	private Course course;
	private Student student;
	private int status;

	public Courseregister() {
	}

	public Courseregister(CourseregisterId id, Course course, Student student, int status) {
		this.id = id;
		this.course = course;
		this.student = student;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idStudent", column = @Column(name = "ID_Student", nullable = false, length = 15) ),
			@AttributeOverride(name = "idCourse", column = @Column(name = "ID_Course", nullable = false) ) })
	public CourseregisterId getId() {
		return this.id;
	}

	public void setId(CourseregisterId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Course", nullable = false, insertable = false, updatable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Student", nullable = false, insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
