package entities;
// Generated Dec 22, 2015 4:16:46 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CourseregisterId generated by hbm2java
 */
@Embeddable
public class CourseregisterId implements java.io.Serializable {

	private String idStudent;
	private int idCourse;

	public CourseregisterId() {
	}

	public CourseregisterId(String idStudent, int idCourse) {
		this.idStudent = idStudent;
		this.idCourse = idCourse;
	}

	@Column(name = "ID_Student", nullable = false, length = 15)
	public String getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(String idStudent) {
		this.idStudent = idStudent;
	}

	@Column(name = "ID_Course", nullable = false)
	public int getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(int idCourse) {
		this.idCourse = idCourse;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseregisterId))
			return false;
		CourseregisterId castOther = (CourseregisterId) other;

		return ((this.getIdStudent() == castOther.getIdStudent()) || (this.getIdStudent() != null
				&& castOther.getIdStudent() != null && this.getIdStudent().equals(castOther.getIdStudent())))
				&& (this.getIdCourse() == castOther.getIdCourse());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdStudent() == null ? 0 : this.getIdStudent().hashCode());
		result = 37 * result + this.getIdCourse();
		return result;
	}

}
