package entities;
// Generated Dec 22, 2015 4:16:46 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "learning")
public class Course implements java.io.Serializable {

	private Integer id;
	private String name;
	private String detail;
	private Date startDate;
	private Date endDate;
	private Set<Assignment> assignments = new HashSet<Assignment>(0);
	private Set<Courseregister> courseregisters = new HashSet<Courseregister>(0);

	public Course() {
	}

	public Course(String name, String detail, Date startDate, Date endDate) {
		this.name = name;
		this.detail = detail;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Course(String name, String detail, Date startDate, Date endDate, Set<Assignment> assignments,
			Set<Courseregister> courseregisters) {
		this.name = name;
		this.detail = detail;
		this.startDate = startDate;
		this.endDate = endDate;
		this.assignments = assignments;
		this.courseregisters = courseregisters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Detail", nullable = false, length = 65535)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "StartDate", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EndDate", nullable = false, length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Assignment> getAssignments() {
		return this.assignments;
	}

	public void setAssignments(Set<Assignment> assignments) {
		this.assignments = assignments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Courseregister> getCourseregisters() {
		return this.courseregisters;
	}

	public void setCourseregisters(Set<Courseregister> courseregisters) {
		this.courseregisters = courseregisters;
	}

}
