package entities;
// Generated Dec 23, 2015 8:10:44 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perform generated by hbm2java
 */
@Entity
@Table(name = "perform", catalog = "learning")
public class Perform implements java.io.Serializable {

	private PerformId id;
	private Assignment assignment;
	private Staff staff;
	private Student student;
	private String file;
	private Integer point;
	private Date uploadDate;
	private int status;

	public Perform() {
	}

	public Perform(PerformId id, Assignment assignment, Student student, String file, Date uploadDate, int status) {
		this.id = id;
		this.assignment = assignment;
		this.student = student;
		this.file = file;
		this.uploadDate = uploadDate;
		this.status = status;
	}

	public Perform(PerformId id, Assignment assignment, Staff staff, Student student, String file, Integer point,
			Date uploadDate, int status) {
		this.id = id;
		this.assignment = assignment;
		this.staff = staff;
		this.student = student;
		this.file = file;
		this.point = point;
		this.uploadDate = uploadDate;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idStudent", column = @Column(name = "ID_Student", nullable = false, length = 15) ),
			@AttributeOverride(name = "idAssignment", column = @Column(name = "ID_Assignment", nullable = false) ) })
	public PerformId getId() {
		return this.id;
	}

	public void setId(PerformId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Assignment", nullable = false, insertable = false, updatable = false)
	public Assignment getAssignment() {
		return this.assignment;
	}

	public void setAssignment(Assignment assignment) {
		this.assignment = assignment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Staff")
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Student", nullable = false, insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "File", nullable = false, length = 100)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@Column(name = "Point")
	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UploadDate", nullable = false, length = 0)
	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
