package entities;
// Generated Dec 23, 2015 8:10:44 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "learning")
public class Staff implements java.io.Serializable {

	private String id;
	private Role role;
	private String password;
	private String name;
	private String email;
	private String address;
	private int status;
	private Set<Perform> performs = new HashSet<Perform>(0);

	public Staff() {
	}

	public Staff(String id, Role role, String password, String name, String email, String address, int status) {
		this.id = id;
		this.role = role;
		this.password = password;
		this.name = name;
		this.email = email;
		this.address = address;
		this.status = status;
	}

	public Staff(String id, Role role, String password, String name, String email, String address, int status,
			Set<Perform> performs) {
		this.id = id;
		this.role = role;
		this.password = password;
		this.name = name;
		this.email = email;
		this.address = address;
		this.status = status;
		this.performs = performs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Role", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "Password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Email", nullable = false, length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Perform> getPerforms() {
		return this.performs;
	}

	public void setPerforms(Set<Perform> performs) {
		this.performs = performs;
	}

}
