package entities;
// Generated Dec 22, 2015 4:16:46 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "learning")
public class Student implements java.io.Serializable {

	private String id;
	private Faculty faculty;
	private String password;
	private String name;
	private Date dob;
	private String address;
	private String email;
	private int status;
	private Set<Perform> performs = new HashSet<Perform>(0);
	private Set<Courseregister> courseregisters = new HashSet<Courseregister>(0);

	public Student() {
	}

	public Student(String id, Faculty faculty, String password, String name, Date dob, String address, String email,
			int status) {
		this.id = id;
		this.faculty = faculty;
		this.password = password;
		this.name = name;
		this.dob = dob;
		this.address = address;
		this.email = email;
		this.status = status;
	}

	public Student(String id, Faculty faculty, String password, String name, Date dob, String address, String email,
			int status, Set<Perform> performs, Set<Courseregister> courseregisters) {
		this.id = id;
		this.faculty = faculty;
		this.password = password;
		this.name = name;
		this.dob = dob;
		this.address = address;
		this.email = email;
		this.status = status;
		this.performs = performs;
		this.courseregisters = courseregisters;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 15)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Faculty", nullable = false)
	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	@Column(name = "Password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", nullable = false, length = 0)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Email", nullable = false, length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<Perform> getPerforms() {
		return this.performs;
	}

	public void setPerforms(Set<Perform> performs) {
		this.performs = performs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<Courseregister> getCourseregisters() {
		return this.courseregisters;
	}

	public void setCourseregisters(Set<Courseregister> courseregisters) {
		this.courseregisters = courseregisters;
	}

}
